GET http://localhost:4000/search/escola HTTP/1.1
content-type: application/json

###
POST http://localhost:4000/search/magnet HTTP/1.1
content-type: application/json

{
    "title": "The Magicians Escola de Magia 3ª Temporada Completa Torrent Dublada e Legendada",
    "link": "https://www.baixafilme.net/the-magicians-escola-de-magia-3a-temporada-completa-torrent-dublada-e-legendada-x01/",
    "site_id": 2
  }
###